version: "3.9"
services:
  main_container:
    build:
      dockerfile: ./Dockerfile
      args:
        - USER_NAME=$USER_NAME
        - USER_UID=$UID
        - USER_GID=$GID
        - CONDA_ENV_NAME=awesome
        - DISPLAY=:16
      context: .
    # user: "1002:1002"
    # image: tutu:latest
    container_name: $CONTAINER_NAME
    stdin_open: false
    network_mode: "host"
    environment:
      - DISPLAY=:16
      - XDG_RUNTIME_DIR=/tmp/runtime-csaintmartin
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: $GPU_COUNT
              capabilities: [gpu]
