version: "3.9"
services:
  main_container:
    build:
      dockerfile: ./Dockerfile
      args:
        - USER_NAME=$USER_NAME
        - USER_UID=$UID
        - USER_GID=$GID
        - CONDA_ENV_NAME=awesome
        - JULIA_RELEASE=1.9.0
        - DISPLAY=$DISPLAY
      context: .
    environment:
      - DISPLAY
    network_mode: "host"
    privileged: true
    # user: "1002:1002"
    # image: tutu:latest
    container_name: $CONTAINER_NAME
    stdin_open: false
    # tty: true        # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: $GPU_COUNT
              capabilities: [gpu]
